Change normal checkout flow, add some field request payload
getivy/magento-2 pull request #8
Opened 2022-11-01 12:34 UTC by MuhibEsparks

Change normal checkout flow, add some field request payload

2022-11-02 18:57 UTC, simontjw requested changes

2022-11-02 18:57 UTC, simontjw commented on Controller/Success/Index.php
> +        // }
```suggestion
```

2022-11-03 10:24 UTC, kostoman approved these changes

2022-11-03 10:24 UTC, kostoman commented on Controller/Checkout/Index.php
> +            // if(!$express)
remove this if its not needed anymore

2022-11-04 13:20 UTC, simontjw approved these changes

2022-11-04 13:20 UTC, merged